config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sk'

  resources :projects
  root 'projects#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  enum status: [:recruiting, :working, :finished]

  validates_uniqueness_of :origin_id, scope: :type

  after_create :load_project_detail

  private
    def load_project_detail
      ProjectWorker.perform_async(self.id)
    end
end

app/models/project/lagou.rb
class Project::Lagou < Project

  def status_parse=(status)
    self.status = case status
                  when '招募中'
                    :recruiting
                  when '执行中'
                    :working
                  when '已完成'
                    :finished
                  end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.recruiting.order(posted_at: :desc).page(params[:page])
  end

  def show
    @project = Project.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # time format with local
  #
  # format :default, :long, :short
  def time_format(time, format = :long)
    I18n.l time, format: format if time.present?
  end

  def time_tag(time)
    content_tag :time, time_format(time), datetime: time.strftime('%FT%R%z') if time.present?
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PartTime</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container grid-sm">

      <div id="Top">
        <%= link_to "小試牛刀", root_path, class: 'logo' %>
      </div>

      <div class="columns" id="Wrapper">
        <%= yield %>
      </div>

      <div id="Footer" class="text-center">
        &copy; 2018
      </div>
    </div>
  </body>
</html>

app/views/projects/index.html.erb
<div class="col-12">
  <ul class="project-list">
    <% @projects.each do |project| %>
      <li>
        <span class="status <%= project.status %>"><%= t "project_status.#{project.status}" %></span>
        <%= link_to project.title, project_path(project) %>
        <%= time_tag project.posted_at %>
      </li>
    <% end %>
  </ul>
</div>

<div class="col-12">
  <%= paginate @projects, window: 2 %>
</div>

app/views/projects/show.html.erb
<div class="col-12 project-detail">
  <h3 class="title"><%= @project.title %></h3>
  <%= time_tag @project.posted_at %>
  <pre><%= @project.body %></pre>
  <%= link_to "来源", @project.origin_url, target: '_blank', class: 'text-gray' %>
</div>